kind: pipeline
type: docker
name: Nobita
clone:
  depth: 1

steps:
- name: Building
  image: z4nyx/docker:latest
  environment:
    bot_token:
      from_secret: bot_token
    chat_id:
      from_secret: chat_id
  commands:
  - bash build.sh